model:
  name: FraudMLP
  type: pytorch
  input_dim: 195
  hidden_dims:
  - 32
  - 32
  dropout: 0.2632
training:
  batch_size: 2048
  epochs: 100
  learning_rate: 0.00029442
  weight_decay: 1.0e-05
  l1_lambda: 3.1e-06
  early_stopping_patience: 10
loss_params:
  type: focal
  focal:
    alpha: 0.587
    gamma: 1.974
  wbce:
    pos_weight: 32.0
