model:
  name: FraudVAE
  type: pytorch
  input_dim: 195
  latent_dim: 16
  hidden_dims:
  - 128
  dropout: 0.1374
training:
  batch_size: 1024
  epochs: 50
  learning_rate: 0.00289029
  weight_decay: 0.0004904
  kld_weight: 0.00012907
  early_stopping_patience: 10
